// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apbd_kol2ef_rev2.Context;

#nullable disable

namespace apbd_kol2ef_rev2.Migrations
{
    [DbContext(typeof(MusicLabelsDbContext))]
    [Migration("20240609222252_DbInit")]
    partial class DbInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataWydania")
                        .HasColumnType("datetime");

                    b.Property<int>("IdWytwornia")
                        .HasColumnType("int");

                    b.Property<string>("NazwaAlbumu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdAlbum");

                    b.HasIndex("IdWytwornia");

                    b.ToTable("Album", (string)null);
                });

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.Muzyk", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Pseudonim")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMuzyk");

                    b.ToTable("Muzyk", (string)null);
                });

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.Utwor", b =>
                {
                    b.Property<int>("IdUtwor")
                        .HasColumnType("int");

                    b.Property<double>("CzasTrwania")
                        .HasColumnType("float");

                    b.Property<int?>("IdAlbum")
                        .HasColumnType("int");

                    b.Property<string>("NazwaUtworu")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdUtwor");

                    b.HasIndex("IdAlbum");

                    b.ToTable("Utwor", (string)null);
                });

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.WykonawcaUtworu", b =>
                {
                    b.Property<int>("IdMuzyk")
                        .HasColumnType("int");

                    b.Property<int>("IdUtwor")
                        .HasColumnType("int");

                    b.HasKey("IdMuzyk", "IdUtwor");

                    b.HasIndex("IdUtwor");

                    b.ToTable("WykonawcaUtworu", (string)null);
                });

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.Wytwornia", b =>
                {
                    b.Property<int>("IdWytwornia")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdWytwornia");

                    b.ToTable("Wytwornia", (string)null);
                });

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.Album", b =>
                {
                    b.HasOne("apbd_kol2ef_rev2.Entities.Wytwornia", "WytworniaNavigation")
                        .WithMany("Albumy")
                        .HasForeignKey("IdWytwornia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("Album_Wytwornia");

                    b.Navigation("WytworniaNavigation");
                });

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.Utwor", b =>
                {
                    b.HasOne("apbd_kol2ef_rev2.Entities.Album", "Album")
                        .WithMany("Utwory")
                        .HasForeignKey("IdAlbum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Album_Utwor");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.WykonawcaUtworu", b =>
                {
                    b.HasOne("apbd_kol2ef_rev2.Entities.Muzyk", "MuzykNavigation")
                        .WithMany("WykonawcyUtwory")
                        .HasForeignKey("IdMuzyk")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("WykonawcaUtworu_Muzyk");

                    b.HasOne("apbd_kol2ef_rev2.Entities.Utwor", "UtworNavigation")
                        .WithMany("WykonawcyUtwory")
                        .HasForeignKey("IdUtwor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("WykonawcaUtworu_Utwor");

                    b.Navigation("MuzykNavigation");

                    b.Navigation("UtworNavigation");
                });

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.Album", b =>
                {
                    b.Navigation("Utwory");
                });

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.Muzyk", b =>
                {
                    b.Navigation("WykonawcyUtwory");
                });

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.Utwor", b =>
                {
                    b.Navigation("WykonawcyUtwory");
                });

            modelBuilder.Entity("apbd_kol2ef_rev2.Entities.Wytwornia", b =>
                {
                    b.Navigation("Albumy");
                });
#pragma warning restore 612, 618
        }
    }
}
